pull_request_rules:
  - name: Automatic merge Dependabot PRs (for actions) on CI success
    conditions:
      - base=main
      - author=dependabot[bot]
      - files~=^.github/workflows/
      - check-success=build
      - "#review-requested=0"
    actions:
      merge:
        method: squash
