char *logorv =
    "              vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv\n"
    "                  vvvvvvvvvvvvvvvvvvvvvvvvvvvv\n"
    "rrrrrrrrrrrrr       vvvvvvvvvvvvvvvvvvvvvvvvvv\n"
    "rrrrrrrrrrrrrrrr      vvvvvvvvvvvvvvvvvvvvvvvv\n"
    "rrrrrrrrrrrrrrrrrr    vvvvvvvvvvvvvvvvvvvvvvvv\n"
    "rrrrrrrrrrrrrrrrrr    vvvvvvvvvvvvvvvvvvvvvvvv\n"
    "rrrrrrrrrrrrrrrrrr    vvvvvvvvvvvvvvvvvvvvvvvv\n"
    "rrrrrrrrrrrrrrrr      vvvvvvvvvvvvvvvvvvvvvv  \n"
    "rrrrrrrrrrrrr       vvvvvvvvvvvvvvvvvvvvvv    \n"
    "rr                vvvvvvvvvvvvvvvvvvvvvv      \n"
    "rr            vvvvvvvvvvvvvvvvvvvvvvvv      rr\n"
    "rrrr      vvvvvvvvvvvvvvvvvvvvvvvvvv      rrrr\n"
    "rrrrrr      vvvvvvvvvvvvvvvvvvvvvv      rrrrrr\n"
    "rrrrrrrr      vvvvvvvvvvvvvvvvvv      rrrrrrrr\n"
    "rrrrrrrrrr      vvvvvvvvvvvvvv      rrrrrrrrrr\n"
    "rrrrrrrrrrrr      vvvvvvvvvv      rrrrrrrrrrrr\n"
    "rrrrrrrrrrrrrr      vvvvvv      rrrrrrrrrrrrrr\n"
    "rrrrrrrrrrrrrrrr      vv      rrrrrrrrrrrrrrrr\n"
    "rrrrrrrrrrrrrrrrrr          rrrrrrrrrrrrrrrrrr\n"
    "rrrrrrrrrrrrrrrrrrrr      rrrrrrrrrrrrrrrrrrrr\n"
    "rrrrrrrrrrrrrrrrrrrrrr  rrrrrrrrrrrrrrrrrrrrrr\n"
    "\n"
    "       INSTRUCTION SETS WANT TO BE FREE\n\n"
    "Hello from ChiselV, a RISC-V Processor!\n\n";

char *logocv =
"(..,,**)                                                                       \n"
" ( #,,***)              MM''''''YMM dP       oo                   dP M''MMMMM''M\n"
"  (,,.,,***)            M' .mmm. 'M 88                            88 M  MMMMM  M\n"
"   (,,,,,,**.)          M  MMMMMooM 88d888b. dP .d8888b. .d8888b. 88 M  MMMMP  M\n"
"     (,,,,,,**,)        M  MMMMMMMM 88'  '88 88 Y8ooooo. 88ooood8 88 M  MMMM' .M\n"
"       ( .,,..*.,)      M. 'MMM' .M 88    88 88       88 88.  ... 88 M  MMP' .MM\n"
"         ( .,,,.., )    MM.     .dM dP    dP dP '88888P' '88888P' dP M     .dMMM\n"
"           (,,.,,.,..)  MMMMMMMMMMM                                  MMMMMMMMMMM\n"
"             (,*,.   ,)                                                         \n"
"               (,*#/#.,)            INSTRUCTION SETS WANT TO BE FREE            \n"
"                  ,###.                                                         \n"
"                    *#*(,                                                       \n"
"                      /((((((((##.                                              \n"
"                    ...*(((((/(/(/##(                                           \n"
"                    .... ((((((((((###                                          \n"
"                      *....,(((((((((((###                                      \n"
"                        .,....(((((((((((###                                    \n"
"                          *....(/((((((((####/                                  \n"
"                            *.,,.,((((((((((((((                                \n"
"                              /.,,,,((#((/(/***                                 \n"
"                                /...((((***                                     \n"
"                                  ,(*/*                                         \n"
"                                                                                \n"
"Hello from ChiselV, a RISC-V Processor!                                         \n";